export const EVENT_ACTION_TYPES = {
  EVENT_LIST_REQUEST: "EVENT_LIST_REQUEST",
  EVENT_LIST_SUCCESS: "EVENT_LIST_SUCCESS",
  EVENT_LIST_FAIL: "EVENT_LIST_FAIL",
};

export const EVENT_INVITE_ACTION_TYPES = {
  EVENT_INVITE_LIST_REQUEST: "EVENT_INVITE_LIST_REQUEST",
  EVENT_INVITE_LIST_SUCCESS: "EVENT_INVITE_LIST_SUCCESS",
  EVENT_INVITE_LIST_FAIL: "EVENT_INVITE_LIST_FAIL",
};

export const USER_LOGIN_ACTION_TYPES = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT ",
};
