export const EVENT_ACTION_TYPES = {
  EVENT_LIST_REQUEST: "EVENT_LIST_REQUEST",
  EVENT_LIST_SUCCESS: "EVENT_LIST_SUCCESS",
  EVENT_LIST_FAIL: "EVENT_LIST_FAIL",
};

export const EVENT_INVITE_ACTION_TYPES = {
  EVENT_INVITE_LIST_REQUEST: "EVENT_INVITE_LIST_REQUEST",
  EVENT_INVITE_LIST_SUCCESS: "EVENT_INVITE_LIST_SUCCESS",
  EVENT_INVITE_LIST_FAIL: "EVENT_INVITE_LIST_FAIL",
};

export const EVENT_INVITE_DELETE_ACTION_TYPES = {
  EVENT_INVITE_DELETE_REQUEST: "EVENT_INVITE_DELETE_REQUEST",
  EVENT_INVITE_DELETE_SUCCESS: "EVENT_INVITE_DELETE_SUCCESS",
  EVENT_INVITE_DELETE_FAIL: "EVENT_INVITE_DELETE_FAIL",
};

export const EVENT_INVITES_ACTION_TYPES = {
  EVENT_INVITES_LIST_REQUEST: "EVENT_INVITES_LIST_REQUEST",
  EVENT_INVITES_LIST_SUCCESS: "EVENT_INVITES_LIST_SUCCESS",
  EVENT_INVITES_LIST_FAIL: "EVENT_INVITES_LIST_FAIL",
};
export const SUBMIT_INVITE_EVENT_ACTION_TYPES = {
  SUBMIT_INVITE_EVENT_REQUEST: "SUBMIT_INVITE_EVENT_REQUEST",
  SUBMIT_INVITE_EVENT_SUCCESS: "SUBMIT_INVITE_EVENT_SUCCESS",
  SUBMIT_INVITE_EVENT_FAIL: "SUBMIT_INVITE_EVENT_FAIL",
};

export const USER_LOGIN_ACTION_TYPES = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT ",
};
